In [4]:
# Array operation
# Sum Operation
import numpy as np

In [8]:
import numpy as np
w = np.array([12,14,16,18,19,45])
print(w)
print(w.sum())


[12 14 16 18 19 45]
124


In [14]:
p1 = np.array([[1,2],[3,2]])
print(p1)
print(p1.sum(axis =0)) #axis =0 columnwise
print(p1.sum(axis =1))  #axis =1 rowwise

[[1 2]
 [3 2]]
[4 4]
[3 5]


In [5]:
# Min max operation
a1 = np.array([1,2,5,67,45,90,78,34,5,6,89,23])
print(a1)
print(a1.min())
print(a1.max())
print(np.min(a1))
print(np.max(a1))

[ 1  2  5 67 45 90 78 34  5  6 89 23]
1
90
1
90


In [12]:
p1 = np.arange(10,22).reshape(3,4)
print(p1)


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [6]:
p1 = np.arange(10,22).reshape(3,4)
print(p1)
print(p1.min(axis=0))
print(np.min(p1,axis=0))
print(np.min(p1,axis =1))
print(np.max(p1,axis=0))
print(np.max(p1,axis =1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[10 11 12 13]
[10 11 12 13]
[10 14 18]
[18 19 20 21]
[13 17 21]


In [18]:
# argmin argmax operation

a1 = np.array([1,2,5,67,45,90,78,34,5,6,89,23])
print(a1)
print(np.argmin(a1))
print(np.argmax(a1))

[ 1  2  5 67 45 90 78 34  5  6 89 23]
0
5


In [9]:
a1 = np.array([1,2,5,67,45,90,78,34,5,6,89,23])
print(a1)  
min_value = a1[np.argmin(a1)]
max_value = a1[np.argmax(a1)]
print("Maximum value is:",max_value)
print("Minimum value is:",min_value)

[ 1  2  5 67 45 90 78 34  5  6 89 23]
Maximum value is: 90
Minimum value is: 1


In [19]:
p1 = np.arange(10,22).reshape(3,4)
print(p1)
print(np.argmin(p1,axis=0))
print(np.argmin(p1,axis =1))
print(np.argmax(p1,axis=0))
print(np.argmax(p1,axis =1))

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
[0 0 0 0]
[0 0 0]
[2 2 2 2]
[3 3 3]


In [11]:
#Sort operation
import numpy as np
p1 = np.array([12,4,47,3,0,20,18,56,24,23,10])
print(p1)
r1 = np.sort(p1)
print(r1)

[12  4 47  3  0 20 18 56 24 23 10]
[ 0  3  4 10 12 18 20 23 24 47 56]


In [16]:
p1 = np.array([12,4,47,3,0,20,18,56,24,23,10])
print(p1)
r1 =np.sort(p1) # ascending order
print(r1)
r2 =np.sort(r1)[::-1] #desending order
print(r2)

[12  4 47  3  0 20 18 56 24 23 10]
[ 0  3  4 10 12 18 20 23 24 47 56]
[56 47 24 23 20 18 12 10  4  3  0]


In [20]:
p1 = np.array([[11,21,18],[25,35,16],[7,14,3]])
print(p1)


[[11 21 18]
 [25 35 16]
 [ 7 14  3]]


In [22]:
p1 = np.array([[11,21,18],[25,35,16],[7,14,3]])
print(p1)
r1 = np.sort(p1,axis=0)
r2 = np.sort(p1,axis =1)
p1 = np.array([[11,21,18],[25,35,16],[7,14,3]])
print(p1)
r3= np.sort(p1,axis=0)[::-1]
r4 = np.sort(p1,axis =1)[::-1]
print(r1)
print(r2)
print(r3)
print(r4)

print(r1)
print(r2)


[[11 21 18]
 [25 35 16]
 [ 7 14  3]]
[[11 21 18]
 [25 35 16]
 [ 7 14  3]]
[[ 7 14  3]
 [11 21 16]
 [25 35 18]]
[[11 18 21]
 [16 25 35]
 [ 3  7 14]]
[[25 35 18]
 [11 21 16]
 [ 7 14  3]]
[[ 3  7 14]
 [16 25 35]
 [11 18 21]]
[[ 7 14  3]
 [11 21 16]
 [25 35 18]]
[[11 18 21]
 [16 25 35]
 [ 3  7 14]]


In [29]:
a1 = np.array([10,12,15,17,18,19,20,22,21,24,25,30])
print(a1)
m1 =np.where(a1%2==0)
print(m1)
print(a1[m1])

[10 12 15 17 18 19 20 22 21 24 25 30]
(array([ 0,  1,  4,  6,  7,  9, 11], dtype=int64),)
[10 12 18 20 22 24 30]


In [30]:
a1 = np.array([10,12,15,17,18,19,20,22,21,24,25,30])
print(a1)
m1 =np.where(a1<20)
print(m1)
print(a1[m1])

[10 12 15 17 18 19 20 22 21 24 25 30]
(array([0, 1, 2, 3, 4, 5], dtype=int64),)
[10 12 15 17 18 19]


In [33]:
a1 = np.array([10,12,15,17,18,19,20,22,21,24,25,30])
print(a1)
m1 = np.where(a1<20,a1+5,a1*2)
print(m1)
m2 = np.where(a1%2==0,a1*4,a1-7)
print(m2)

[10 12 15 17 18 19 20 22 21 24 25 30]
[15 17 20 22 23 24 40 44 42 48 50 60]
[ 40  48   8  10  72  12  80  88  14  96  18 120]


In [19]:
p1 = np.array([[10,12,16],[4,5,6],[8,9,10]])
print(p1)
r1 = np.where(p1<12)
print(r1)
print(p1[r1])

[[10 12 16]
 [ 4  5  6]
 [ 8  9 10]]
(array([0, 1, 1, 1, 2, 2, 2], dtype=int64), array([0, 0, 1, 2, 0, 1, 2], dtype=int64))
[10  4  5  6  8  9 10]


In [20]:
a1 = np.array([10,12,15,17,18,19,20,22,21,24,25,30])
print(a1)
m1 = np.extract(a1%3==0,a1)
print(m1)

[10 12 15 17 18 19 20 22 21 24 25 30]
[12 15 18 21 24 30]


In [41]:
a1 = np.array([10,12,15,17,18,19,20,22,21,24,25,30])
print(a1)
m1 = np.extract(a1<30,a1)
print(m1)

[10 12 15 17 18 19 20 22 21 24 25 30]
[10 12 15 17 18 19 20 22 21 24 25]


In [43]:

p1 = np.array([[10,12,16],[4,5,6],[8,9,10]])
print(p1)
r1 = np.extract(p1<10,p1)
print(r1)

[[10 12 16]
 [ 4  5  6]
 [ 8  9 10]]
[4 5 6 8 9]


In [22]:
z1 = np.array([1,2,3,4,5])
z2 = np.array([6,7,8,9,10])
r1 = np.concatenate([z1,z2])
print(r1)

[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
z1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(z1)
z2 = np.array([[16,17,18,19,20],[21,22,23,24,25]])
print(z2)
r = np.concatenate([z1,z2],axis=0)
print(r)
r1 = np.concatenate([z1,z2],axis =1)
print(r1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 1  2  3  4  5 16 17 18 19 20]
 [ 6  7  8  9 10 21 22 23 24 25]]


In [24]:
z1 = np.array([1,2,3,4,5])
z2 = np.array([6,7,8,9,10])
print(z1)
print(z2)
r = np.hstack([z1,z2])
print(r)
r1 = np.vstack([z1,z2])
print(r1)

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [31]:
import numpy as np
z1 = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
print(z1)
p1 = np.vsplit(z1,2)
print(p1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]]), array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])]
