In [2]:
# Linear algebra
import numpy as np
a = np.array([[1,2,3],[2,3,4],[4,5,3]])
b = np.array([20,27,40])
print(a)
print(b)
res = np.linalg.solve(a,b)
print(res)


[[1 2 3]
 [2 3 4]
 [4 5 3]]
[20 27 40]
[-5.66666667 12.33333333  0.33333333]


In [8]:
a = np.array([[1,2],[3,4]])
b = np.array([18,20])
print(a)
print(b)
res =np.linalg.solve(a,b)
print(res)

[[1 2]
 [3 4]]
[18 20]
[-16.  17.]


In [9]:
# Dot product

a = np.array([[1,2,3],[2,3,4],[4,5,3]])
b =np.array([[5,6,7],[2,3,4],[6,7,8]])
print(a)
print(b)
res = np.dot(a,b)
print(res)

[[1 2 3]
 [2 3 4]
 [4 5 3]]
[[5 6 7]
 [2 3 4]
 [6 7 8]]
[[27 33 39]
 [40 49 58]
 [48 60 72]]


In [10]:
# matrix inverse

q = np.array([[1,2],[3,4]])
print(q)
res = np.linalg.inv(q)
print(res)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [11]:
r1 = np.dot(q,res)
print(r1)

[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [5]:
# Determinant

q = np.array([[4,2],[3,4]])
print(q)
Det = np.linalg.det(q)
print("Determinant of matrix is:",round(Det))
print(Det)

[[4 2]
 [3 4]]
Determinant of matrix is: 10
10.000000000000002


In [18]:
# Trace

a = np.array([[1,2,3],[2,3,4],[4,5,3]])
print(a)
Trace = np.trace(a)
print("Trace of matrix:",Trace)

[[1 2 3]
 [2 3 4]
 [4 5 3]]
Trace of matrix: 7


In [19]:
# Eigen value Eigen vector

a = np.array([[1,2,3],[2,3,4],[4,5,3]])
print(a)
eig_value,eig_vector = np.linalg.eig(a)
print("Eigen value:",eig_value)
print("Eigen vector:",eig_vector)

[[1 2 3]
 [2 3 4]
 [4 5 3]]
Eigen value: [ 9.29420244 -0.15057759 -2.14362484]
Eigen vector: [[-0.39717242 -0.70822963 -0.47325443]
 [-0.57881098  0.68186461 -0.41871397]
 [-0.71220216 -0.18295203  0.7750541 ]]
