In [1]:

import numpy as np


In [12]:
# np.array
w =np.array([2,5,4,8,9,1,10])
print(w)
print(type(w))
print(w.dtype)
print(w.shape)
print(w.size)
print(w.ndim)

[ 2  5  4  8  9  1 10]
<class 'numpy.ndarray'>
int32
(7,)
7
1


In [5]:
a =[5,6,8,9,7,1]
b =(10,5,64,78,9)
print(a)
print(b)
m1 = np.array(a)
m2 = np.array(b)
print(m1)
print(m2)

[5, 6, 8, 9, 7, 1]
(10, 5, 64, 78, 9)
[5 6 8 9 7 1]
[10  5 64 78  9]


In [14]:
w2 = np.array([[2,5,9,8,6,7,8,1],[4,5,8,9,6,3,1,4]])
print(w2)
print(w2.dtype)
print(w2.size)
print(w2.shape)
print(w2.ndim)


[[2 5 9 8 6 7 8 1]
 [4 5 8 9 6 3 1 4]]
int32
16
(2, 8)
2


In [13]:
m =np.array([[[5,6,7,9,1,20,6],[8,9,7,56,12,5,6]],[[2,5,8,9,9,9,10],[5,6,7,8,9,4,2]]])
print(m)
print(m.dtype)
print(m.size)
print(m.shape)
print(m.ndim)

[[[ 5  6  7  9  1 20  6]
  [ 8  9  7 56 12  5  6]]

 [[ 2  5  8  9  9  9 10]
  [ 5  6  7  8  9  4  2]]]
int32
28
(2, 2, 7)
3


In [ ]:
# arange

In [21]:
a1 = np.arange(10,20)
print(a1)
print(a1.dtype)
print(a1.size)
print(a1.shape)
print(a1.ndim)

[10 11 12 13 14 15 16 17 18 19]
int32
10
(10,)
1


In [17]:
a2 = np.arange(5,20,2)
print(a2)

[ 5  7  9 11 13 15 17 19]


In [19]:
a3 = np.arange(50,1,-5)
print(a3)

[50 45 40 35 30 25 20 15 10  5]


In [ ]:
# zeros

In [22]:
b1 = np.zeros((3,4))
print(b1)
print(b1.dtype)
print(b1.size)
print(b1.shape)
print(b1.ndim)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64
12
(3, 4)
2


In [23]:
b2=np.zeros((3,3),dtype='int')
print(b2)


[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [25]:
# ones
c1 = np.ones((3,4))
print(c1)
print(c1.dtype)
print(c1.size)
print(c1.shape)
print(c1.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
12
(3, 4)
2


In [26]:
c2=np.ones((3,3),dtype='int')
print(c2)


[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [28]:
# reshape
d1 =np.array([5,2,4,9,6,7,8,9,1,10,8,9])
print(d1)
d =d1.reshape(3,4)
print(d)

[ 5  2  4  9  6  7  8  9  1 10  8  9]
[[ 5  2  4  9]
 [ 6  7  8  9]
 [ 1 10  8  9]]


In [30]:
d2 =np.array([5,6,3,7,8,9,7,9]).reshape(2,4)
print(d2)



[[5 6 3 7]
 [8 9 7 9]]


In [39]:
a =np.array([5,6,8,7])
b =np.array([5,6,7,8])
print(a*b)


[25 36 56 56]


In [36]:
# linspace 

e1 = np.linspace(2,10,4)
print(e1)
print(e1.dtype)
print(e1.size)
print(e1.shape)
print(e1.ndim)



[ 2.          4.66666667  7.33333333 10.        ]
float64
4
(4,)
1


In [37]:
e2 = np.linspace(10,50,10,dtype ='int')
print(e2)

[10 14 18 23 27 32 36 41 45 50]


In [40]:
e3 = np.linspace(1,100,10,dtype =int)
print(e3)

[  1  12  23  34  45  56  67  78  89 100]


In [47]:
# copy
a =np.array([2,7,8,9,5])
a1 = a.copy()
print(a)
print(a1)
a[0]=8
print(a)
print(a1)

[2 7 8 9 5]
[2 7 8 9 5]
[8 7 8 9 5]
[2 7 8 9 5]


In [48]:
# view

a =np.array([2,7,8,9,5])
a1 = a.view()
print(a)
print(a1)
a[0]=8
print(a)
print(a1)

[2 7 8 9 5]
[2 7 8 9 5]
[8 7 8 9 5]
[8 7 8 9 5]


In [ ]:
# Random
# np.random.random

In [54]:
x = np.random.random((3,4))
print(x)
x1 = np.random.random((3,4,2))
print(x1)

[[0.9019277  0.90022142 0.99110262 0.21353247]
 [0.32979306 0.56667565 0.01585441 0.92499039]
 [0.26905706 0.54916995 0.58099216 0.62836624]]
[[[0.39487511 0.66602474]
  [0.64820556 0.03565531]
  [0.57707012 0.59786379]
  [0.07196192 0.05355831]]

 [[0.44969739 0.02130741]
  [0.4170649  0.67090713]
  [0.14800754 0.02756916]
  [0.69927624 0.0961885 ]]

 [[0.68143225 0.51866615]
  [0.4391519  0.91289656]
  [0.07691053 0.484707  ]
  [0.56254989 0.90473367]]]


In [ ]:
# np.random.randint

In [57]:
y = np.random.randint(2,20,5)
print(y)

[17 13 10 15  7]


In [58]:
y1 = np.random.randint(5,50,20)
print(y1)

[23  8 15 46 42 13  7 11 38  6 39 43 27 46 12 24 30 12 31 27]


In [ ]:
# np.random.randn

In [62]:
z1 =np.random.randn(2,10)
print(z1)

[[ 0.91565878  0.14846121  1.48365372 -0.18368817 -1.40572176  0.79441985
   1.74178425  0.31819716  0.57182253 -0.77153716]
 [-0.75389896  0.56381174 -0.14030508 -0.95842861  1.38893107 -0.04265525
  -0.53728892 -0.20944156 -0.24555173  0.95290146]]


In [63]:
# np.random.choice

z2 = np.random.choice([4,5,6,6,7,9,1,5],size=4)
print(z2)

[4 5 1 9]
